// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1, arg2) {
  return window['go']['toolkit']['HttpClient']['Delete'](arg1, arg2);
}

export function Get(arg1, arg2) {
  return window['go']['toolkit']['HttpClient']['Get'](arg1, arg2);
}

export function Post(arg1, arg2) {
  return window['go']['toolkit']['HttpClient']['Post'](arg1, arg2);
}

export function PostForm(arg1, arg2) {
  return window['go']['toolkit']['HttpClient']['PostForm'](arg1, arg2);
}

export function Put(arg1, arg2) {
  return window['go']['toolkit']['HttpClient']['Put'](arg1, arg2);
}

export function SetHeader(arg1) {
  return window['go']['toolkit']['HttpClient']['SetHeader'](arg1);
}

export function Startup(arg1) {
  return window['go']['toolkit']['HttpClient']['Startup'](arg1);
}
