// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Delete(arg1:string,arg2:any):Promise<any>;

export function Get(arg1:string,arg2:{[key: string]: string}):Promise<any>;

export function Post(arg1:string,arg2:any):Promise<any>;

export function PostForm(arg1:string,arg2:any):Promise<any>;

export function Put(arg1:string,arg2:any):Promise<any>;

export function SetHeader(arg1:{[key: string]: string}):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
