// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {entity} from '../models';

export function Close():Promise<void>;

export function GetConfig():Promise<model.HttpResult>;

export function SetConfig(arg1:entity.Config):Promise<model.HttpResult>;
