// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['PlanBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['PlanBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['PlanBiz']['Edit'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['PlanBiz']['Get'](arg1);
}

export function GetGroupList() {
  return window['go']['biz']['PlanBiz']['GetGroupList']();
}

export function GetList() {
  return window['go']['biz']['PlanBiz']['GetList']();
}

export function Page(arg1) {
  return window['go']['biz']['PlanBiz']['Page'](arg1);
}
