// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['RecordBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['RecordBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['RecordBiz']['Edit'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['RecordBiz']['Get'](arg1);
}

export function Page(arg1) {
  return window['go']['biz']['RecordBiz']['Page'](arg1);
}
