// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['biz']['TaskBiz']['Add'](arg1);
}

export function Delete(arg1) {
  return window['go']['biz']['TaskBiz']['Delete'](arg1);
}

export function Edit(arg1) {
  return window['go']['biz']['TaskBiz']['Edit'](arg1);
}

export function ExecStep(arg1) {
  return window['go']['biz']['TaskBiz']['ExecStep'](arg1);
}

export function Get(arg1) {
  return window['go']['biz']['TaskBiz']['Get'](arg1);
}

export function GetList() {
  return window['go']['biz']['TaskBiz']['GetList']();
}

export function GetSystemList() {
  return window['go']['biz']['TaskBiz']['GetSystemList']();
}

export function InitBrowser() {
  return window['go']['biz']['TaskBiz']['InitBrowser']();
}

export function Page(arg1) {
  return window['go']['biz']['TaskBiz']['Page'](arg1);
}
